---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsk.
--- DateTime: 2018/10/22 10:19 PM
---

local app = {
    ---init from unity
    writePath = nil,
    buildinResPath = nil,
    resPath = nil,
    cfgPath = nil,
    gameObject = nil,
    component = nil,

    ---init in lua
    scheduler = nil,
    poolMgr = nil,
    logger = nil,
}

function app.Init()


    --以后所有的代码，不能直接访问未初始化的全局变量
    --require("Strict")

    --初始化系统各个模块
    app.scheduler = require("Scheduler")
    app.poolMgr = require("ObjectPool")
    app.logger = require("Logger")

    print(app.writePath)

    app.logger:EnableFileAppender(app.writePath)
    app.logger:Debug("debug")
    app.logger:Warn("warn")
    app.logger:Error("error")
end


function app.Dispose()

end

return app