---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SK.
--- DateTime: 2018/11/27 15:33
--- 资源列表管理器

local task = require("Res.LoadTask")

local function CreateResInfo()
    ---@class ResInfo
    ---@field resKey string
    ---@field url string
    ---@field name string
    ---@field mainAssetName string
    ---@field assetType string
    ---@field hash string
    ---@field crc number
    ---@field dependences string[]
    local t = {resKey = nil,
               url = nil,
               name= nil,
               mainAssetName = nil,
               assetType = nil,
               hash = nil,
               crc=0,
               dependences = {}}
    return t
end


function ResInfoManager(manifestUrl)
    ---@class ResInfoManager
    ---@field GetAllRemapDependencies fun(self:ResInfoManager,url:string):table<number,string>
    ---@field GetResInfo fun(self:ResInfoManager,url:string):ResInfo
    local ResInfoHandler = {}

    ---资源信息
    ---@type table<string,ResInfo>
    local infos = {}

    function ResInfoHandler:GetAllRemapDependencies(url)
    end

    function ResInfoHandler:GetResInfo(url)
        return infos and infos[url] or nil
    end

    return ResInfoHandler
end